## Promise 内置对象

**Promise** 对象代表了一个异步操作的最终完成或者失败、及其结果值。

#### 语法：

```js
new Promise( function(resolve, reject) {...} /* executor */  );
```

**`executor：`**`executor` 是带有 `resolve` 和 `reject` 两个参数的函数 。

1. **`Promise`构造函数执行时立即调用`executor` 函数（ 函数在Promise构造函数返回所建实例对象前被调用）**。

2. `resolve` 和 `reject` 函数被调用时，分别将`promise`的状态改为`fulfilled（完成）`或`rejected（失败）`，如果在`executor`函数中抛出一个错误，那么该 `promise` 状态为 `rejected`。

#### 举例：

我们经常使用的返回`Promise`对象的函数：

```js
function myAsyncFunction(url) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.onload = () => resolve(xhr.responseText);
    xhr.onerror = () => reject(xhr.statusText);
    xhr.send();
  });
};
```

#### 描述：

`Promise` 对象是一个代理对象（代理一个未来的结果值），被代理的值在`Promise`对象创建时可能是未知的。它允许你为异步操作的成功和失败分别绑定相应的`处理方法（handlers）`。 

这让异步方法可以像同步方法那样返回值，但并不是立即返回最终执行结果，而是一个能代表未来出现的结果的`promise`对象。

一个 `Promise`有以下几种状态：

- **pending**：初始状态，既不是成功，也不是失败状态。
- **fulfilled**：意味着操作成功完成。
- **rejected**：意味着操作失败。

`pending `状态的 `Promise` 对象可能会变为`fulfilled `状态并传递一个值给相应的状态处理方法，也可能变为`rejected`并传递失败信息。当其中任一种情况出现时，`Promise` 对象的 `then` 方法绑定的`处理方法（handlers ）`就会被调用（then方法包含两个参数：`onfulfilled 和 onrejected`，它们都是` Function `类型。

因为 `Promise.prototype.then` 和 `Promise.prototype.catch` 方法返回`promise `对象， 所以它们可以被链式调用。

![img](assets/promises.png)

改变`promise`状态和指定回调函数谁先谁后都有可能，正常情况下是先指定回调再改变状态, 但也可以先改状态再指定回调。如果先指定的回调, 那当状态发生改变时, 回调函数就会调用, 得到数据。如果先改变的状态, 那当指定回调时, 回调函数就会调用, 得到数据。

#### 约定:

不同于“老式”的传入回调，在使用 `Promise` 时，会有以下约定：

1. 在本轮 [事件循环](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/EventLoop#执行至完成) 运行完成之前，回调函数是不会被调用的。
2. 即使异步操作已经完成（成功或失败），在这之后通过 [`then()` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)添加的回调函数也会被调用，换句话说，回调函数调用触发的时间与异步操作完成时间点并不相关，`Promise`可以将异步的结果存储起来。
3. 通过多次调用 `then()` 可以添加多个回调函数，它们会按照插入顺序执行，后面我会详细的介绍链式调用。

#### 属性：

 `Promise.length`：`length`属性，其值总是为 1 (构造器参数的数目)。

 [`Promise.prototype`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/prototype)：表示 `Promise` 构造器的原型。

#### 方法：

[1.`Promise.all(iterable)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)：

这个方法返回一个新的`promise`对象，该`promise`对象在`iterable`参数对象里所有的`promise`对象都成功的时候才会触发成功，一旦有任何一个`iterable`里面的`promise`对象失败则立即触发该`promise`对象的失败。

这个新的`promise`对象在触发成功状态以后，会把一个包含`iterable`里所有`promise`返回值的数组作为成功回调的返回值，顺序跟`iterable`的顺序一致；如果这个新的`promise`对象触发了失败状态，它会把`iterable`里第一个失败的`promise`对象的错误信息作为它的失败错误信息。`Promise.all`方法常被用于处理多个`promise`对象的状态集合。

[2.`Promise.race(iterable)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/race)：

当`iterable`参数里的任意一个子`promise`被成功或失败后，父`promise`马上也会用子`promise`的成功返回值或失败详情作为参数调用父`promise`绑定的相应句柄，并返回该`promise`对象。

[3.`Promise.reject(reason)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject)：

返回一个状态为失败的`Promise`对象，并将给定的失败信息传递给对应的处理方法

[4.`Promise.resolve(value)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)：

返回一个状态由给定`value`决定的`Promise`对象。如果该值是`thenable`(即，带有`then`方法的对象)，返回的`Promise`对象的最终状态由`then`方法执行决定；否则的话(该`value`为空，基本类型或者不带`then`方法的对象)，返回的`Promise`对象状态为`fulfilled`，并且将该`value`传递给对应的`then`方法。通常而言，如果你不知道一个值是否是`Promise`对象，使用`Promise.resolve(value)` 来返回一个`Promise`对象,这样就能将该`value`以`Promise`对象形式使用。

## Promise 原型

#### 属性：

`Promise.prototype.constructor`：返回被创建的实例函数.  默认为 [`Promise`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise) 函数.

#### 方法：

[1.`Promise.prototype.catch(onRejected)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch)：

添加一个`拒绝(rejection) `回调到当前 `promise`, 返回新的`promise`。当这个回调函数被调用，新 `promise` 将以它的返回值来`resolve`，否则如果当前`promise `进入`fulfilled`状态，则以当前`promise`的完成结果作为新`promise`的完成结果.

[2.`Promise.prototype.then(onFulfilled, onRejected)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)：

添加`解决(fulfillment)`和`拒绝(rejection)`回调到当前 `promise`, 返回一个新的 `promise`, 将以回调返回值来`resolve`.

[3.`Promise.prototype.finally(onFinally)`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)：

添加一个事件处理回调于当前`promise`对象，并且在原`promise`对象解析完毕后，返回一个新的`promise`对象。回调会在当前`promise`运行完毕后被调用，无论当前`promise`的状态是`完成(fulfilled)还是失败(rejected)`。

## 链式调用

在过去，要想做多重的异步操作，会导致经典的回调地狱：

```js
doSomething(function(result) {
  doSomethingElse(result, function(newResult) {
    doThirdThing(newResult, function(finalResult) {
      console.log('Got the final result: ' + finalResult);
    }, failureCallback);
  }, failureCallback);
}, failureCallback);
```

现在，我们可以把回调绑定到返回的 Promise 上，形成一个 Promise 链：

```js
doSomething().then(function(result) {
  return doSomethingElse(result);
})
.then(function(newResult) {
  return doThirdThing(newResult);
})
.then(function(finalResult) {
  console.log('Got the final result: ' + finalResult);
})
.catch(failureCallback);
```

#### 规则：

首先`Promise.prototype.then(onFulfilled, onRejected)`会返回一个新的`promise`，这个`promise`的结果状态由`then()`指定的回调函数执行的结果决定：

1. 如果抛出异常, 新`promise`变为`rejected`, `reason`为抛出的异常。
2. 如果返回的是非`promise`的任意值, 新`promise`变为`resolved`，` value`为返回的值。
3. 如果返回的是另一个新`promise`， 此`promise`的结果就会成为新`promise`的结果。

```js
new Promise((resolve, reject) => {
    // resolve(1)
    reject(1)
}).then(
    value => {
        console.log('onResolved1()', value)
        // return 2
        // return Promise.resolve(3)
        // return Promise.reject(4)
        throw 5
    },
    reason => {
        console.log('onRejected1()', reason)
        // return 2
        // return Promise.resolve(3)
        // return Promise.reject(4)
        throw 5
    }
).then(
    value => {
        console.log('onResolved2()', value)
    },
    reason => {
        console.log('onRejected2()', reason)
    }
)
```

如何串联新的异步任务，因为`.then`返回的状态已经是指定好的，所以要在里面添加异步任务必须使用`Promise`封装，不然无法改变返回结果。

```js
new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log("执行任务1(异步)")
        resolve(1)
    }, 1000);
}).then(
    value => {
        console.log('任务1的结果: ', value)
        console.log('执行任务2(同步)')
        return 2
    }
).then(
    value => {
        console.log('任务2的结果:', value)

        return new Promise((resolve, reject) => {
            // 启动任务3(异步)
            setTimeout(() => {
                console.log('执行任务3(异步))')
                resolve(3)
            }, 1000);
        })
    }
).then(
    value => {
        console.log('任务3的结果: ', value)
    }
)
```

对于链式调用中的异常处理，只要在链条的末尾布置一个`.catch`就可以将链条中的错误传递下去，实际的过程是递进的不是跳跃的，原理是因为每个`promise`都有一个默认的`onRejected`的回调。

```js
new Promise((resolve, reject) => {
    // resolve(1)
    reject(1)
}).then(
    value => {
        console.log('onResolved1()', value)
        return 2
    },
    // reason => {throw reason} （默认）
).then(
    value => {
        console.log('onResolved2()', value)
        return 3
    },
    reason => {
        throw reason
    }
).then(
    value => {
        console.log('onResolved3()', value)
    },
    reason => Promise.reject(reason)
).catch(reason => {
    console.log('onReejected1()', reason)
    // throw reason
    // return Promise.reject(reason)
    return new Promise(()=>{}) // 返回一个pending的promise  中断promise链
})
```

## Promise 的实现

> **注意：**下面实现的将回调加入队列使用的是`setTimeOut`这其实是不正确的，因为加入的是宏队列而不是微队列。

要实现一个Promise函数，首先我们看看原生的Promise函数，大概包含如下属性`（有省略）`。

```js
Promise {<pending>}
	__proto__: Promise
    catch: ƒ catch()
    constructor: ƒ Promise()
    finally: ƒ finally()
    then: ƒ then()
  [[PromiseStatus]]: "resolved"
  [[PromiseValue]]: 1
```

可以看到`Promise`函数用`[[PromiseStatus]]`和`[[PromiseValue]]`保存异步操作的结果以及其类型，同时`Promise`应该还会用一个类似数组的队列来储存回调函数，当`Promise`封装的异步操作执行结束之后，会一个一个的将回调函数添加到事件循环当中，通过这些我们能构建出`Promise`的大体框架。

```js
const PENDING 	= Symbol("pending");
const FULLFILL 	= Symbol("fullfil");
const REJECT 		= Symbol("reject");

export default class Promise {
  constructor( ) {
    this.status = "pending";		// 存储状态
    this.data = undefined;			// 存储结果
    this.callbacks = [];				// 回调函数队列
    try {
      excutor(this._resolve.bind(this), this._reject.bind(this));	
      // 不绑定this的话会隐式丢失，因为我们传入的是函数的引用没携带上下文。
    } catch (error) {
      this._reject(error);		 	// 如果Promise封装的异步操作报错则立刻改变状态为reject。
    }
  }
  /**
   * 用于改变当前 promise 的结果以及状态值
   * @param {any} value
   */
  _resolve(value) {
    if (this.status != PENDING) return; // 一个Promise只能初始化一次。
    this.status = FULLFILL;							// 改变状态
    this.data = value;									// 记录结果
    setTimeout(() => {									// 执行回调函数（添加到事件循环当中）
      this.callbacks.forEach((callbackObj) => {
        callbackObj.onResolved(value);
      });
    });
  }
  _reject(reason) {
    if (this.status != PENDING) return;
    this.status = REJECT;
    this.data = reason;
    setTimeout(() => {
      this.callbacks.forEach((callbackObj) => {
        callbackObj.onRejected(reason);
      });
    });
  }
}

```

`Promise`对象构建完成之后我们还需要提供一个添加回调函数的方法`then`，对于添加的回调函数一般有两种执行时间点：

一种是`Promise`内的操作为同步操作时，回调函数在`Promise`结果计算完成之后被添加，此时我们要根据父Promise的异步执行结果来手动处理回调函数，需要将其添加到事件循环当中。

另一种是`Promise`内的操作时异步操作，回调函数在结果计算未完前被添加，这种情况下我们需要把回调添加到父`Promsie`的队列里，当父`Promise`的结果计算完成之后回调会自动执行。

同时我们还要知道`then`方法返回的并不是完全的父`Promise`构造的对象，而是一个新的子级`Promise`，这个`Promise`的执行结果是由传进`then`方法的回调函数的执行结果来决定的。如果说传进`then`方法的回调函数的结果是一个 `promise` 对象，那么会将这个 `promise` 的计算结果给到 `then` 方法产生的子级 `promise`。

同时`then`方法的两个回调函数参数要有默认值，来将父级`Promise`的结果传递下去。

```js
class Promise {
  /**
   * @param {function(values)} onResolved
   * @param {function(reason)} onRejected
   * @returns {Promise}
   */
  then(onResolved, onRejected) {
    onResolved =
      typeof onResolved === "function" ? onResolved : (value) => value;
    onRejected =
      typeof onRejected === "function"
        ? onRejected
        : (reason) => {
            throw reason;
          };
    let self = this;
    return new Promise((resolve, reject) => {
      function handle(callback) {
        try {
          // 使用父 Promise 的结果值来执行新 Promise 的回调函数计算新 Promise 的异步结果
          const result = callback(self.data);
          if (result instanceof Promise) {
            // 如果回调函数返回了一个新的 Promise，
            // 将这个 `promise` 的计算结果给到 `then` 方法产生的子级 `promise`。
            // 原理就是 `onresolve` 其实是子 `promise` 的 `resolve`。
            result.then(resolve, reject);
          } else {
            // 新 Promise 的异步执行结果
            resolve(result);
          }
        } catch (error) {
          reject(error);
        }
      }
      // 如果说是 pending 状态说明异步操作的结果还没有得出，所以此时我们要把回调函数添加到原来的队列里去。
      if (self.status === PENDING) {
        self.callbacks.push({
          onResolved(value) {
            // 同样的我们要用原来的结果执行子Promise的回调函数。
            handle(onResolved);
          },
          onRejected(reason) {
            handle(onRejected);
          },
        });
        // 如果说是 fullfill 或者 reject 状态说明父 Promise 的异步结果已经得出，这是我们要将新的回调函数添加到事件循环中。
      } else if (self.status === FULLFILL) {
        setTimeout(() => {
          // 使用父 Promise的结果值来执行新Promise的回调函数计算新 Promise 的异步结果。
          handle(onResolved);
        });
      } else {
        setTimeout(() => {
          handle(onRejected);
        });
      }
    });
  }
}
```

接下来的`catch`就可以在then的基础上简单的实现：

```js
class Promise {
  catch(onRejected) {
    return this.then(undefined, onRejected)
  }
}
```

在之后我们要实现两个构造函数方法`resolve`和`reject`他们两个返回已经计算完的`Promise`实例：

```js
class Promise {
    static resolve(value) {
    return new Promise((resolve, reject) => {
      if (value instanceof Promise) {
        return value.then(resolve, reject);
      } else {
        resolve(value);
      }
    });
  }
  static reject(reason) {
    return new Promise((resolve, reject) => {
      reject(reason);
    });
  }
}
```

